package mm;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.lang.annotation.RetentionPolicy;

/**
 * Annotation to exclude generated code from coverage reports.
 * <p>
 * This annotation is used to mark classes, methods, or constructors that are
 * generated by tools or frameworks and should not be included in code coverage
 * analysis.
 * </p>
 * <p>
 * It is typically used for classes that extend JavaFX components or other
 * framework-specific classes that do not require coverage.
 * </p>
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.TYPE, ElementType.METHOD, ElementType.CONSTRUCTOR})
public @interface Generated {
}